-- Test templates for document system
-- Adding practical test templates for users

-- 1. Student Notice Template
INSERT INTO document_templates (name, category, description, template_content, fields, file_type, is_system, created_at) VALUES
('Student Notice', 'student_management', 'General student notice template for grades, activities, etc.',
'{"type": "html", "content": "<div><h2>{{noticeTitle}}</h2><p>Dear {{parentName}}:</p><p>Hello! We would like to inform you about your child {{studentName}} (Class {{className}}) regarding the following:</p><p>{{noticeContent}}</p><p>{{additionalInfo}}</p><p>If you have any questions, please contact the class teacher.</p><div><p>{{schoolName}}</p><p>Class Teacher: {{teacherName}}</p><p>Phone: {{teacherPhone}}</p><p>{{noticeDate}}</p></div></div>"}',
'{"noticeTitle": {"label": "Notice Title", "type": "text", "required": true}, "parentName": {"label": "Parent Name", "type": "text", "required": true}, "studentName": {"label": "Student Name", "type": "text", "required": true}, "className": {"label": "Class Name", "type": "text", "required": true}, "noticeContent": {"label": "Notice Content", "type": "textarea", "required": true}, "additionalInfo": {"label": "Additional Info", "type": "textarea"}, "schoolName": {"label": "School Name", "type": "text", "required": true}, "teacherName": {"label": "Teacher Name", "type": "text", "required": true}, "teacherPhone": {"label": "Phone Number", "type": "text", "required": true}, "noticeDate": {"label": "Notice Date", "type": "date", "required": true}}',
'pdf,word,html', 1, datetime('now'));

-- 2. Parent Meeting Notice
INSERT INTO document_templates (name, category, description, template_content, fields, file_type, is_system, created_at) VALUES
('Parent Meeting Notice', 'parent_communication', 'Parent meeting notification template with time, location and agenda',
'{"type": "html", "content": "<div><h2>Parent Meeting Notice</h2><p>Dear {{className}} parents:</p><p>Hello! To strengthen home-school communication, we will hold a parent meeting on {{meetingDate}}.</p><p><strong>Time:</strong> {{meetingDate}} {{meetingTime}}</p><p><strong>Location:</strong> {{meetingLocation}}</p><p><strong>Topic:</strong> {{meetingTopic}}</p><p><strong>Agenda:</strong> {{meetingContent}}</p><p><strong>Notes:</strong> {{meetingNotes}}</p><p>Please attend on time!</p><div><p>{{schoolName}}</p><p>{{className}} Teacher: {{teacherName}}</p><p>{{noticeDate}}</p></div></div>"}',
'{"className": {"label": "Class Name", "type": "text", "required": true}, "meetingDate": {"label": "Meeting Date", "type": "date", "required": true}, "meetingTime": {"label": "Meeting Time", "type": "time", "required": true}, "meetingLocation": {"label": "Meeting Location", "type": "text", "required": true}, "meetingTopic": {"label": "Meeting Topic", "type": "text", "required": true}, "meetingContent": {"label": "Meeting Content", "type": "textarea", "required": true}, "meetingNotes": {"label": "Notes", "type": "textarea", "required": true}, "schoolName": {"label": "School Name", "type": "text", "required": true}, "teacherName": {"label": "Teacher Name", "type": "text", "required": true}, "noticeDate": {"label": "Notice Date", "type": "date", "required": true}}',
'pdf,word,html', 1, datetime('now'));

-- 3. Student Leave Request
INSERT INTO document_templates (name, category, description, template_content, fields, file_type, is_system, created_at) VALUES
('Student Leave Request', 'student_management', 'Student leave application form template',
'{"type": "html", "content": "<div><h2>Student Leave Request</h2><p><strong>Class:</strong> {{className}} <strong>Name:</strong> {{studentName}}</p><p><strong>Student ID:</strong> {{studentId}} <strong>Application Date:</strong> {{applyDate}}</p><p><strong>Reason for Leave:</strong></p><p>{{reason}}</p><p><strong>Leave Period:</strong> {{startDate}} to {{endDate}} ({{days}} days)</p><p><strong>Parent Phone:</strong> {{parentPhone}}</p><div><p>Student Signature: _____________</p><p>Parent Signature: _____________</p><p>Teacher Signature: _____________</p></div></div>"}',
'{"className": {"label": "Class Name", "type": "text", "required": true}, "studentName": {"label": "Student Name", "type": "text", "required": true}, "studentId": {"label": "Student ID", "type": "text", "required": true}, "applyDate": {"label": "Application Date", "type": "date", "required": true}, "reason": {"label": "Reason for Leave", "type": "textarea", "required": true}, "startDate": {"label": "Start Date", "type": "date", "required": true}, "endDate": {"label": "End Date", "type": "date", "required": true}, "days": {"label": "Number of Days", "type": "number", "required": true}, "parentPhone": {"label": "Parent Phone", "type": "text", "required": true}}',
'pdf,word,html', 1, datetime('now'));

-- 4. Class Activity Plan
INSERT INTO document_templates (name, category, description, template_content, fields, file_type, is_system, created_at) VALUES
('Class Activity Plan', 'activity_management', 'Class activity planning template',
'{"type": "html", "content": "<div><h1>{{activityTitle}}</h1><h3>Basic Information</h3><p><strong>Activity Title:</strong> {{activityTitle}}</p><p><strong>Date:</strong> {{activityDate}} {{activityTime}}</p><p><strong>Location:</strong> {{activityLocation}}</p><p><strong>Class:</strong> {{className}}</p><p><strong>Teacher in Charge:</strong> {{teacherName}}</p><h3>Purpose</h3><p>{{activityPurpose}}</p><h3>Schedule</h3><p>{{activityProcess}}</p><h3>Materials</h3><p>{{materials}}</p><h3>Notes</h3><p>{{notes}}</p><div><p>Planner: {{plannerName}}</p><p>Plan Date: {{planDate}}</p></div></div>"}',
'{"activityTitle": {"label": "Activity Title", "type": "text", "required": true}, "activityDate": {"label": "Activity Date", "type": "date", "required": true}, "activityTime": {"label": "Activity Time", "type": "time", "required": true}, "activityLocation": {"label": "Activity Location", "type": "text", "required": true}, "className": {"label": "Class Name", "type": "text", "required": true}, "teacherName": {"label": "Teacher in Charge", "type": "text", "required": true}, "activityPurpose": {"label": "Activity Purpose", "type": "textarea", "required": true}, "activityProcess": {"label": "Activity Schedule", "type": "textarea", "required": true}, "materials": {"label": "Materials Needed", "type": "textarea", "required": true}, "notes": {"label": "Notes", "type": "textarea", "required": true}, "plannerName": {"label": "Planner Name", "type": "text", "required": true}, "planDate": {"label": "Plan Date", "type": "date", "required": true}}',
'pdf,word,html', 1, datetime('now'));

-- 5. Grade Report
INSERT INTO document_templates (name, category, description, template_content, fields, file_type, is_system, created_at) VALUES
('Grade Report', 'grade_management', 'Student grade report template',
'{"type": "html", "content": "<div><h2>Grade Report</h2><p><strong>Student:</strong> {{studentName}} <strong>Class:</strong> {{className}}</p><p><strong>Student ID:</strong> {{studentId}} <strong>Exam:</strong> {{examName}}</p><p><strong>Exam Date:</strong> {{examDate}}</p><table border=\"1\"><tr><th>Subject</th><th>Score</th><th>Grade</th><th>Notes</th></tr><tr><td>Chinese</td><td>{{chineseScore}}</td><td>{{chineseGrade}}</td><td>{{chineseNote}}</td></tr><tr><td>Math</td><td>{{mathScore}}</td><td>{{mathGrade}}</td><td>{{mathNote}}</td></tr><tr><td>English</td><td>{{englishScore}}</td><td>{{englishGrade}}</td><td>{{englishNote}}</td></tr></table><p><strong>Total Score:</strong> {{totalScore}} <strong>Class Rank:</strong> {{classRank}}</p><p><strong>Teacher Comments:</strong> {{teacherComment}}</p><div><p>Class Teacher: {{teacherName}}</p><p>{{noticeDate}}</p></div></div>"}',
'{"studentName": {"label": "Student Name", "type": "text", "required": true}, "className": {"label": "Class Name", "type": "text", "required": true}, "studentId": {"label": "Student ID", "type": "text", "required": true}, "examName": {"label": "Exam Name", "type": "text", "required": true}, "examDate": {"label": "Exam Date", "type": "date", "required": true}, "chineseScore": {"label": "Chinese Score", "type": "number"}, "chineseGrade": {"label": "Chinese Grade", "type": "text"}, "chineseNote": {"label": "Chinese Notes", "type": "text"}, "mathScore": {"label": "Math Score", "type": "number"}, "mathGrade": {"label": "Math Grade", "type": "text"}, "mathNote": {"label": "Math Notes", "type": "text"}, "englishScore": {"label": "English Score", "type": "number"}, "englishGrade": {"label": "English Grade", "type": "text"}, "englishNote": {"label": "English Notes", "type": "text"}, "totalScore": {"label": "Total Score", "type": "number"}, "classRank": {"label": "Class Rank", "type": "number"}, "teacherComment": {"label": "Teacher Comments", "type": "textarea"}, "teacherName": {"label": "Teacher Name", "type": "text", "required": true}, "noticeDate": {"label": "Notice Date", "type": "date", "required": true}}',
'pdf,word,html', 1, datetime('now'));